### ISSUE TITLE
Have pages for scanner/alert/plugin types

### ISSUE THREAD

**Issue by rezen** [zaproxy/zaproxy-website#43]
For custom reports, it would be nice to able to link to a reference of all the scanner plugins' details. There could be a page that lists them all and then individual pages for each plugin. For each plugin we can create an entry and then have the templates generate a table with links to each individual plugin.

| id    | name       | cweid      | wascid | tags    | more |
|-------|------------|------------|--------|---------|------|
| 10020 | Xframe ... | 16         | 15     | headers |      |

```yaml
---
type: plugin
pluginid: 10020
name: Xframe....
----

Description down under here?
```
