### ISSUE TITLE
Social Previews for Site Content

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy-website#45]
We need to figure out how to enable social previews of site content (primarily for Twitter and Slack I believe, but LinkedIn might also be a good move). I don't think we really have much Facebook, Youtube, etc activity. Though if simple enough we shouldn't ignore them.

Some regs:
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards
- https://brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/
- https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
- https://gohugo.io/templates/internal/

Looks like we should be adding this to: https://github.com/zaproxy/zaproxy-website/blob/master/site/layouts/_default/baseof.html

**Comment by kingthorin** [comment]
Did a quick test, for twitter it does seem to be as simple as adding `{{ template "_internal/twitter_cards.html" . }}` to `/site/layouts/_default/baseof.html`. 

Of course I could only check by viewing page source and seeing that the metatags were generated and inserted, but that seems positive. For images it's also possible to include an offsite image, so like for ZAPping the Top 10 we could use the following front matter:

```yaml
---
title: "ZAPping the OWASP Top 10"
description: "This document gives an overview of the automatic and manual components provided by the OWASP Zed Attack Proxy Project (ZAP) that are recommended for testing each of the OWASP Top Ten Project 2017 risks."
images:
- https://raw.githubusercontent.com/OWASP/Top10/master/2017/images/OWASP-Top-10.png
type: page
date: "2020-01-30"
---
```
